SELECT
    FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM
    REST_INFO r1
WHERE
    FAVORITES = (
        SELECT MAX(FAVORITES)
        FROM REST_INFO r2
        WHERE r2.FOOD_TYPE = r1.FOOD_TYPE
    )
ORDER BY
    FOOD_TYPE DESC;
