SELECT 
    MONTH(a.START_DATE) AS MONTH, a.CAR_ID, COUNT(*) AS RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY a
WHERE
    a.START_DATE BETWEEN '2022-08-01' AND '2022-10-31' AND
    a.CAR_ID IN (
        SELECT 
            CAR_ID
        FROM 
            CAR_RENTAL_COMPANY_RENTAL_HISTORY b
        WHERE
            b.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
        GROUP BY
            b.CAR_ID
        HAVING
            COUNT(*) >= 5
    )
GROUP BY
    MONTH(a.START_DATE), a.CAR_ID
ORDER BY
    MONTH, a.CAR_ID DESC;
