SELECT
    CAR_ID,
    ROUND(AVG(RENTAL_DURATION), 1) AS AVERAGE_DURATION
FROM
    (
        SELECT 
            CAR_ID,
            DATEDIFF(END_DATE, START_DATE) + 1 AS RENTAL_DURATION
         FROM
            CAR_RENTAL_COMPANY_RENTAL_HISTORY
    ) AS RENTAL_DURATIONS
GROUP BY
    CAR_ID
HAVING
    AVERAGE_DURATION >= 7
ORDER BY
    AVERAGE_DURATION DESC, CAR_ID DESC;
