SELECT
    DISTINCT CAR_ID
FROM
    CAR_RENTAL_COMPANY_CAR
JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
USING
    (CAR_ID)
WHERE
    MONTH(START_DATE) = 10
    AND CAR_TYPE = '세단'
ORDER BY
    CAR_ID DESC;
