SELECT
    u.USER_ID, u.NICKNAME, SUM(b.PRICE) AS TOTAL_SALES
FROM
    USED_GOODS_USER u
JOIN 
    USED_GOODS_BOARD b
ON 
    u.USER_ID = b.WRITER_ID
WHERE
    STATUS = 'DONE'
GROUP BY
    u.USER_ID
HAVING
    TOTAL_SALES >= 700000
ORDER BY
    TOTAL_SALES;
