SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR, 
    (i.MAX_SIZE_OF_COLONY - SIZE_OF_COLONY) AS YEAR_DEV, 
    ID
FROM
    ECOLI_DATA o
JOIN
    (
        SELECT
            YEAR(DIFFERENTIATION_DATE) AS YEAR, 
            MAX(SIZE_OF_COLONY) MAX_SIZE_OF_COLONY
        FROM
            ECOLI_DATA 
        GROUP BY
            YEAR(DIFFERENTIATION_DATE)
    ) i
ON
    YEAR(o.DIFFERENTIATION_DATE) = i.YEAR
ORDER BY
    YEAR, YEAR_DEV;
